# Gradle settings
# Increase memory available to Gradle, enable parallelism, and enable caching
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.warning.mode=all

# Mod properties
maven_group=io.github.steveplays28
archives_base_name=noisium
mod_id=noisium
mod_namespace=noisium
mod_name=Noisium
mod_description=Optimises worldgen performance for a better gameplay experience.
mod_license=LGPL-3.0
mod_version=2.7.2
supported_minecraft_version=1.21.10
supported_minecraft_version_name=1.21.10

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
min_minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.13-SNAPSHOT

# Dependencies
fabric_version=0.138.0+1.21.10
mod_menu_version=16.0.0-rc.1